name: Terraform Validate

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-validate:
    name: "Terraform Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform code
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        run: terraform validate
